[package]
name = "rhc"
version = "0.18.1"
edition = "2021"

[dependencies]
regex = "1"
phf = { version = "0.11", features = ["macros"] }
num_cpus = "1.15.0"

[dev-dependencies]
assert_cmd = "2.0.7"
predicates = "2.1.5"
