on:
  workflow_call:
    inputs:
      version-type:
        required: true
        type: string
    outputs:
      version:
        description: The new version number
        value: ${{ jobs.bump.outputs.version }}    

permissions:
  actions: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - name: bump version
      run: ./bump.sh $ {{ inputs.version-type }}
    - name: Get version
      id: release
      run: |
        version=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml)
        echo "version=$version" >> $GITHUB_OUTPUT
    - name: Commit new version
      env: 
        CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
        CI_COMMIT_AUTHOR: Continuous Integration
      run: |
        git config --global user.name "Versioning"
        git config --global user.email "github@action.noreply.github.com"
        git add Cargo.toml
        git commit -m "Bumped to ${{ steps.release.outputs.version }}"
        git push     
    outputs:
      version: ${{ steps.release.outputs.version }}   